//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeoulStay_V2._0.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPrices
    {
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public long ItemID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Price { get; set; }
        public long CancellationPolicyID { get; set; }
    
        public virtual CancellationPolicies CancellationPolicies { get; set; }
        public virtual Items Items { get; set; }
    }
}
