//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeoulStay_V2._0.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public long UserID { get; set; }
        public long TransactionTypeID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string GatewayReturnID { get; set; }
    
        public virtual TransactionTypes TransactionTypes { get; set; }
    }
}
